import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useApp } from "../context/AppContext";
import {
  AlertTriangle,
  ArrowRight,
  BadgeCheck,
  Building2,
  Clock3,
  Eye,
  EyeOff,
  SendHorizonal,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
} from "lucide-react";
import { api } from "../api";
import { prepareDemoDataset } from "../demo";
import type {
  AccessAudit,
  AccessGrant,
  ConsentBundle,
  SensitiveCategory,
} from "../types";
import { PatientSearchSelect } from "../components/PatientSearchSelect";
import {
  Badge,
  Card,
  EmptyState,
  GhostButton,
  PrimaryButton,
} from "../components/ui";

const CATEGORY_COPY: Record<SensitiveCategory, { title: string }> = {
  NONE: { title: "General care" },
  MENTAL_HEALTH: { title: "Mental health" },
  REPRODUCTIVE_HEALTH: { title: "Reproductive health" },
  SUBSTANCE_USE: { title: "Substance use" },
  HIV_STATUS: { title: "HIV status" },
  INTIMATE_PARTNER_VIOLENCE: { title: "IPV-related" },
};

function statusTone(status: AccessGrant["status"]) {
  if (status === "ACTIVE") return "teal" as const;
  if (status === "PENDING") return "amber" as const;
  return "red" as const;
}

function visibilityTone(v: string) {
  if (v === "VISIBLE") return "teal" as const;
  if (v === "CLINICIAN_ONLY") return "neutral" as const;
  return "amber" as const;
}

export default function ConsentDashboard() {
  const navigate = useNavigate();
  const { session } = useApp();
  const [searchParams, setSearchParams] = useSearchParams();

  const [selectedPatientId, setSelectedPatientId] = useState<string>(
    searchParams.get("patientId") ?? "",
  );
  const [bundle, setBundle] = useState<ConsentBundle | null>(null);
  const [patientName, setPatientName] = useState("");
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Request access form
  const [requestReason, setRequestReason] = useState("");

  // Break-glass form
  const [emergencyReason, setEmergencyReason] = useState("");
  const [breakGlassConfirm, setBreakGlassConfirm] = useState(false);

  const consentLoadSeq = useRef(0);

  // ── Data loading ──────────────────────────────────────────────────────────

  useEffect(() => {
    const patientId = searchParams.get("patientId");
    if (patientId && patientId !== selectedPatientId) {
      setSelectedPatientId(patientId);
    }
  }, [searchParams, selectedPatientId]);

  useEffect(() => {
    if (!selectedPatientId) {
      setBundle(null);
      setPatientName("");
      return;
    }
    let mounted = true;
    const seq = ++consentLoadSeq.current;
    setLoading(true);
    setError(null);
    api
      .getConsent(selectedPatientId)
      .then((result) => {
        if (!mounted || seq !== consentLoadSeq.current) return;
        setBundle({
          profile: result.profile,
          rules: result.rules,
          grants: result.grants,
          audits: result.audits,
        });
        setPatientName(result.patient.displayName);
      })
      .catch((err: any) => {
        if (!mounted || seq !== consentLoadSeq.current) return;
        setError(String(err?.message || err));
      })
      .finally(() => {
        if (mounted && seq === consentLoadSeq.current) setLoading(false);
      });
    return () => { mounted = false; };
  }, [selectedPatientId]);

  // ── Derived ───────────────────────────────────────────────────────────────
  const myInstitution = session?.institutionName ?? "";

  /** The grant for THIS clinician's institution specifically */
  const myGrant = useMemo(
    () => bundle?.grants.find((g) => g.institutionName === myInstitution) ?? null,
    [bundle, myInstitution],
  );

  /** Audits generated by this institution, newest first */
  const myAudits = useMemo(
    () =>
      (bundle?.audits ?? [])
        .filter((a) => a.institutionName === myInstitution)
        .slice()
        .reverse(),
    [bundle, myInstitution],
  );

  const grantStats = useMemo(() => {
    const grants = bundle?.grants ?? [];
    return {
      active: grants.filter((g) => g.status === "ACTIVE").length,
      pending: grants.filter((g) => g.status === "PENDING").length,
      revoked: grants.filter((g) => g.status === "REVOKED").length,
    };
  }, [bundle]);

  // ── Actions ───────────────────────────────────────────────────────────────
  async function loadDemo() {
    const patientId = await prepareDemoDataset();
    setSearchParams({ patientId });
    setSelectedPatientId(patientId);
    navigate(`/consent?patientId=${patientId}`, { replace: true });
  }

  async function submitAccessRequest() {
    if (!selectedPatientId || !requestReason.trim()) return;
    setSaving(true);
    setError(null);
    try {
      const res = await api.requestAccess(selectedPatientId, {
        institutionName: myInstitution,
        reason: requestReason.trim(),
      });
      setBundle({ profile: res.profile, rules: res.rules, grants: res.grants, audits: res.audits });
      setRequestReason("");
    } catch (err: any) {
      setError(String(err?.message || err));
    } finally {
      setSaving(false);
    }
  }

  async function submitEmergencyAccess() {
    if (!selectedPatientId || !emergencyReason.trim() || !breakGlassConfirm) return;
    setSaving(true);
    setError(null);
    try {
      await api.requestEmergencyAccess(selectedPatientId, {
        institutionName: myInstitution,
        actorName: session?.authorName ?? "Clinician",
        role: session?.role ?? "CLINICIAN",
        reason: emergencyReason.trim(),
        category: bundle?.rules.find((r) => r.visibility === "EMERGENCY_ONLY")?.category,
      });
      const refreshed = await api.getConsent(selectedPatientId);
      setBundle({
        profile: refreshed.profile,
        rules: refreshed.rules,
        grants: refreshed.grants,
        audits: refreshed.audits,
      });
      setEmergencyReason("");
      setBreakGlassConfirm(false);
    } catch (err: any) {
      setError(String(err?.message || err));
    } finally {
      setSaving(false);
    }
  }

  // ── Render ────────────────────────────────────────────────────────────────
  return (
    <div className="space-y-6">
      {/* Page header */}
      <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4">
        <div>
          <Badge tone="teal">clinician workflow</Badge>
          <h1 className="mt-3 text-2xl font-semibold tracking-tight">
            Consent &amp; Access
          </h1>
          <p className="mt-1 text-sm text-slate-500 max-w-xl">
            Request access to a patient's record, log emergency overrides, and
            review your institution's audit trail. Patients control visibility
            settings in their own portal.
          </p>
        </div>
        <button
          onClick={loadDemo}
          className="inline-flex items-center gap-2 rounded-lg border border-teal-200 bg-teal-50 px-4 py-2.5 text-sm font-medium text-teal-700 hover:bg-teal-100 transition shrink-0"
        >
          <Sparkles size={16} />
          Load demo patient
        </button>
      </div>

      {/* Patient selector */}
      <Card className="p-5">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <p className="eyebrow">Patient</p>
            <h2 className="text-lg font-semibold mt-1">
              {patientName || "Choose a patient"}
            </h2>
          </div>
          <PatientSearchSelect
            value={selectedPatientId || null}
            onChange={(id) => {
              const next = id ?? "";
              setSelectedPatientId(next);
              setSearchParams(next ? { patientId: next } : {});
            }}
          />
        </div>

        {/* Access status stats — read-only */}
        {bundle && (
          <div className="grid sm:grid-cols-3 gap-3 mt-5">
            {[
              { label: "Granted", value: grantStats.active, sub: "active institutions", tone: "teal" },
              { label: "Pending", value: grantStats.pending, sub: "awaiting patient approval", tone: "amber" },
              { label: "Revoked", value: grantStats.revoked, sub: "denied or withdrawn", tone: "red" },
            ].map(({ label, value, sub }) => (
              <div key={label} className="rounded-xl border border-slate-200 p-3">
                <p className="eyebrow">{label}</p>
                <p className="mt-2 text-2xl font-semibold">{value}</p>
                <p className="text-xs text-slate-500">{sub}</p>
              </div>
            ))}
          </div>
        )}
      </Card>

      <div className="grid grid-cols-1 xl:grid-cols-[1.25fr_0.75fr] gap-6">
        {/* ── Left column ── */}
        <div className="space-y-6">

          {/* Request Access */}
          <Card className="p-5">
            <div className="flex items-center gap-3 mb-1">
              <Building2 size={18} className="text-teal-600" />
              <p className="eyebrow">Request access</p>
            </div>
            <h2 className="text-lg font-semibold mb-1">Ask the patient for access</h2>
            <p className="text-sm text-slate-500 mb-4">
              Submits a consent request under <span className="font-medium text-slate-700">{myInstitution || "your institution"}</span>.
              The patient will see this in their portal and must approve before you can read their record.
            </p>

            {!bundle ? (
              <EmptyState
                title={loading ? "Loading..." : "Select a patient first"}
                body="Choose a patient from the selector above."
              />
            ) : myGrant && myGrant.status !== "REVOKED" ? (
              <div className="rounded-xl border border-slate-200 p-4 flex items-center gap-4">
                <BadgeCheck size={20} className={myGrant.status === "ACTIVE" ? "text-teal-600" : "text-amber-500"} />
                <div>
                  <p className="font-medium text-sm">
                    {myGrant.status === "ACTIVE"
                      ? "Access granted — your institution can read this record."
                      : "Access request pending — waiting for patient approval."}
                  </p>
                  {myGrant.reason && (
                    <p className="text-xs text-slate-500 mt-0.5">Reason on file: {myGrant.reason}</p>
                  )}
                </div>
                <span className="ml-auto shrink-0">
                  <Badge tone={statusTone(myGrant.status)}>{myGrant.status.toLowerCase()}</Badge>
                </span>
              </div>
            ) : (
              <div className="space-y-3">
                <textarea
                  value={requestReason}
                  onChange={(e) => setRequestReason(e.target.value)}
                  placeholder="Clinical reason for access (e.g. 'Patient transferred to our ICU, need full history for treatment planning')"
                  className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm min-h-[100px] focus:border-teal-500 focus:ring-1 focus:ring-teal-500 transition"
                />
                <PrimaryButton
                  onClick={submitAccessRequest}
                  disabled={saving || !requestReason.trim()}
                  className="inline-flex items-center gap-2"
                >
                  <SendHorizonal size={15} />
                  {saving ? "Submitting..." : "Submit access request"}
                </PrimaryButton>
              </div>
            )}
          </Card>

          {/* Sensitive data visibility — READ ONLY */}
          <Card className="p-5">
            <div className="flex items-center justify-between gap-4 mb-4">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <Eye size={16} className="text-slate-400" />
                  <p className="eyebrow">Data visibility summary</p>
                </div>
                <h2 className="text-lg font-semibold">Patient-set privacy rules</h2>
              </div>
              <Badge tone="neutral">read-only</Badge>
            </div>
            <p className="text-sm text-slate-500 mb-4">
              These settings are controlled by the patient in their portal. You can see the current state but cannot change it.
            </p>

            {!bundle ? (
              <EmptyState title={loading ? "Loading..." : "Select a patient"} />
            ) : (
              <div className="space-y-2">
                {/* Care-team & emergency override — read only badges */}
                <div className="flex flex-wrap gap-2 mb-3">
                  <span className={`inline-flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs font-medium ${
                    bundle.profile.shareWithCareTeam
                      ? "border-teal-200 bg-teal-50 text-teal-700"
                      : "border-slate-200 text-slate-500"
                  }`}>
                    {bundle.profile.shareWithCareTeam ? "✓" : "✗"} Share with care team
                  </span>
                  <span className={`inline-flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs font-medium ${
                    bundle.profile.allowEmergencyOverride
                      ? "border-amber-200 bg-amber-50 text-amber-700"
                      : "border-slate-200 text-slate-500"
                  }`}>
                    {bundle.profile.allowEmergencyOverride ? "✓" : "✗"} Emergency override allowed
                  </span>
                </div>

                {/* Per-category labels */}
                <div className="grid gap-2">
                  {bundle.rules
                    .filter((r) => r.category !== "NONE")
                    .map((rule) => (
                      <div
                        key={rule.id}
                        className="flex items-center justify-between gap-3 rounded-xl border border-slate-100 bg-slate-50 px-4 py-3"
                      >
                        <div className="flex items-center gap-2">
                          {rule.visibility === "VISIBLE" ? (
                            <Eye size={14} className="text-teal-600" />
                          ) : (
                            <EyeOff size={14} className="text-slate-400" />
                          )}
                          <p className="text-sm font-medium">
                            {CATEGORY_COPY[rule.category].title}
                          </p>
                        </div>
                        <Badge tone={visibilityTone(rule.visibility)}>
                          {rule.visibility.replace(/_/g, " ").toLowerCase()}
                        </Badge>
                      </div>
                    ))}
                </div>

                {bundle.profile.patientNote && (
                  <div className="mt-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600 italic">
                    Patient note: "{bundle.profile.patientNote}"
                  </div>
                )}
              </div>
            )}
          </Card>

          {/* All institutions — read-only view */}
          {bundle && bundle.grants.length > 0 && (
            <Card className="p-5">
              <div className="flex items-center justify-between gap-4 mb-4">
                <div>
                  <p className="eyebrow">Network access list</p>
                  <h2 className="text-lg font-semibold mt-1">All institutions on record</h2>
                </div>
                <Badge tone="neutral">read-only</Badge>
              </div>
              <div className="space-y-2">
                {bundle.grants.map((grant) => (
                  <div key={grant.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 px-4 py-3">
                    <div>
                      <p className="text-sm font-medium">
                        {grant.institutionName}
                        {grant.institutionName === myInstitution && (
                          <span className="ml-2 text-[10px] font-mono text-teal-600 bg-teal-50 border border-teal-200 rounded-full px-2 py-0.5">you</span>
                        )}
                      </p>
                      <p className="text-xs text-slate-500 mt-0.5">
                        {grant.level.toLowerCase()} access · {grant.grantedBy ?? "patient portal"}
                      </p>
                    </div>
                    <Badge tone={statusTone(grant.status)}>{grant.status.toLowerCase()}</Badge>
                  </div>
                ))}
              </div>
            </Card>
          )}
        </div>

        {/* ── Right column ── */}
        <div className="space-y-6">

          {/* Break-glass emergency access */}
          <Card className="p-5 border-red-200 bg-red-50">
            <div className="flex items-center gap-2 mb-1">
              <ShieldAlert size={18} className="text-red-600" />
              <p className="eyebrow text-red-700">Break-glass access</p>
            </div>
            <h2 className="text-lg font-semibold mb-2 text-red-900">Emergency override</h2>

            <div className="rounded-xl border border-red-200 bg-white px-4 py-3 mb-4 flex items-start gap-2.5">
              <AlertTriangle size={15} className="text-red-600 mt-0.5 shrink-0" />
              <p className="text-xs text-red-700 leading-5">
                <strong>This access will be permanently logged and reviewed.</strong> Use only when a patient
                is unable to consent and immediate access is clinically necessary. Misuse is a serious
                policy violation.
              </p>
            </div>

            {!selectedPatientId ? (
              <p className="text-sm text-slate-500">Select a patient to enable emergency access.</p>
            ) : (
              <div className="space-y-3">
                <textarea
                  value={emergencyReason}
                  onChange={(e) => setEmergencyReason(e.target.value)}
                  className="w-full rounded-xl border border-red-200 bg-white px-3 py-2.5 text-sm min-h-[90px] focus:border-red-400 focus:ring-1 focus:ring-red-300 transition"
                  placeholder="Mandatory: clinical reason (e.g. 'Patient unconscious, required for emergency treatment')"
                />

                <label className="flex items-start gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={breakGlassConfirm}
                    onChange={(e) => setBreakGlassConfirm(e.target.checked)}
                    className="mt-0.5 accent-red-600"
                  />
                  <span className="text-xs text-red-800 leading-5">
                    I confirm this is a genuine clinical emergency and understand this action is permanently audited.
                  </span>
                </label>

                <button
                  onClick={submitEmergencyAccess}
                  disabled={saving || !emergencyReason.trim() || !breakGlassConfirm}
                  className="w-full inline-flex items-center justify-center gap-2 rounded-lg bg-red-600 hover:bg-red-700 text-white px-4 py-2.5 text-sm font-semibold transition disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <ShieldAlert size={16} />
                  {saving ? "Recording..." : "Record emergency access"}
                </button>
              </div>
            )}
          </Card>

          {/* My institution's audit trail */}
          <Card className="p-5">
            <div className="flex items-center justify-between gap-4 mb-4">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <Clock3 size={15} className="text-slate-400" />
                  <p className="eyebrow">Audit trail</p>
                </div>
                <h2 className="text-lg font-semibold">Your institution's actions</h2>
              </div>
              <Badge tone="neutral">{myInstitution ? "filtered" : "all"}</Badge>
            </div>

            <div className="space-y-2 max-h-[420px] overflow-y-auto scrollbar-thin pr-1">
              {!bundle ? (
                <p className="text-sm text-slate-400">Select a patient to see audit events.</p>
              ) : myAudits.length === 0 ? (
                <EmptyState
                  title="No actions yet"
                  body="Your institution has not accessed or requested access to this patient's record."
                />
              ) : (
                myAudits.map((audit: AccessAudit) => (
                  <div
                    key={audit.id}
                    className={`rounded-xl border p-3 ${
                      audit.emergency
                        ? "border-red-200 bg-red-50"
                        : "border-slate-200"
                    }`}
                  >
                    <div className="flex items-center justify-between gap-2 text-[11px] text-slate-400 font-mono">
                      <span>{new Date(audit.createdAt).toLocaleString()}</span>
                      {audit.emergency && (
                        <span className="text-red-600 font-semibold">break-glass</span>
                      )}
                    </div>
                    <p className="text-sm font-medium mt-1 capitalize">
                      {audit.action.replace(/_/g, " ").toLowerCase()}
                    </p>
                    <p className="text-xs text-slate-500 mt-0.5">
                      {audit.actorName} · {audit.role.toLowerCase()}
                    </p>
                    {audit.reason && (
                      <p className="text-xs text-slate-600 mt-2 italic">"{audit.reason}"</p>
                    )}
                  </div>
                ))
              )}
            </div>
          </Card>

          {error && (
            <Card className="p-4 border-red-200 bg-red-50">
              <p className="text-sm text-red-700">{error}</p>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}
